### ISSUE TITLE
Edicy.ImgDropArea doesn't work as expected

### ISSUE THREAD

**Issue by matsjoonas** [Voog/voog#14]
## Expected Behavior
The examples given here, should work: https://www.voog.com/developers/scripting/examples/image-drop-area 

## Current Behavior
Using the "positionable: true" setting in the Edicy.ImgDropArea breaks it.

## Steps to Reproduce (for bugs)
Visit this test site: https://release20181024-test.voog.com/blogi/minu-esimene-artikkel

Notice the "Uncaught TypeError: this.el.addClass is not a function" in your browser console.
I've copy pasted the Edicy.ImgDropArea snippet from https://www.voog.com/developers/scripting/examples/image-drop-area into the template-tools component. 
It's a fresh Voog site and no other modifications have been made to it.

## Context
Some functionality of our clients' sites is affected due to this.

## Your Environment
Tested on various browsers, i.e latest Chrome, Safari, FF, Edge.

**Comment by matsjoonas** [comment]
Forgot to mention that you have to be logged in to see the image drop area at https://release20181024-test.voog.com/blogi/minu-esimene-artikkel

**Comment by tambeta** [comment]
We found the problem and the fix is in review. This will ~~probably be deployed as a hotfix~~ be part of the planned release this week. Thanks for reporting!
