### ISSUE TITLE
When deleting product from store UI, the list rendered still contains said product.

### ISSUE THREAD

**Issue by randohinn** [Voog/voog#5]
## Expected Behavior

When deleting a product from the UI, the list that you are sent afterwards should not contain the product, that you just deleted. Right now it does, and since no success message is displayed, it's hard to tell if you've actually deleted the product before refreshing the page.

## Current Behavior

Currently, after confirming the delete, you are presented with a list that still contains the element that you just deleted. It's clickable too, but goes nowhere.

## Steps to Reproduce (for bugs)

1. Delete a product from the store UI
2. See product still in list

**Comment by tanelj** [comment]
Fixed on live
